### ISSUE TITLE
The Video on the main page of the site uses out dated commands

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#119] opened 2019-08-19 19:09 UTC
#### Describe the bug
The video on the site uses out dated commands, a new on needs to be recorded with the correct commands being issues.  It mislead a customer

#### Expected behavior
see above

#### Actual behavior
see above

#### Steps to reproduce the bug
3. Scroll to '....'

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by alohr51** [comment] 2019-09-04 17:52
duplicate of kabanero-io/blogs/issues/12

**Closed as completed** 2019-09-04 17:52 UTC
Labels: duplicate
