### ISSUE TITLE
Make the "copy code" icon in Code Blocks persistent

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/kabanero-website#272] opened 2019-10-23 19:05 UTC
#### Describe the bug
There is a copy code icon in the Guides, see the attached screen. It only appears on mouse hover. 

#### Expected behavior
Please make the icon persistent. Sometimes a user may not have their mouse in the code block.
![Screen Shot 2019-10-23 at 11 34 21 AM](https://user-images.githubusercontent.com/27782410/67425736-75f9a680-f58d-11e9-93d9-66fa24e4327c.png)

#### Steps to reproduce the bug
3. Scroll to '....'

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by KyeMaloy97** [comment] 2019-11-04 14:18
After a preliminary look into this issue, it seems theres some javascript responsible for the showing and hiding of the button. I will look into removing it and see how difficult that will be.

**Comment by marikaj123** [comment] 2020-01-15 23:58
@KyeMaloy97 and @kidus60 - what is the status of this bug issue?

**Comment by KyeMaloy97** [comment] 2020-01-20 09:55
@marikaj123 I haven't been working on this at the moment, it looked to be pretty complex to sort as the site uses a lot of javascript, @kidus60 is still assigned so may have some more info?

**Comment by kidus60** [comment] 2020-01-20 10:41
@marikaj123 @KyeMaloy97 the issue was a bit complex and I picked up a higher priority issue so I haven’t been working on it either but I’ll go back and continue making progress today.

**Comment by marikaj123** [comment] 2020-01-21 16:20
According to Kidus, the issue is fixed and the PR is waiting to be merged.

**Closed as completed** 2020-01-21 17:02 UTC
Labels: bug
