### ISSUE TITLE
Table of Contents overlays on last section of guide and is not usable

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-website#288] opened 2019-11-06 15:33 UTC
When viewing this guide, the table of contents does not display until I scroll down to the very  last section, and then it's displayed as overlapping with the guide contents.  In that location, the TOC is also not clickable.  

Reference URL where I see this issue: https://kabanero.io/guides/working-with-collections/#testing-a-collection-locally
Reference attached image:
![TOC issue](https://user-images.githubusercontent.com/54442260/68311985-5def5000-0080-11ea-8520-400c62e98ebb.JPG)

Update: Same issue exists on the other two collection guides.

**Comment by SueChaplain** [comment] 2019-11-07 10:54
I can't reproduce this in Chrome with this document (AsciiDoc source), but I do see it on a Guide I've built from Markdown source. Problems must be related, so I won't open a separate issue. We're looking at the markdown one here and will post an update.

**Comment by nastacio** [comment] 2019-11-07 14:22
I can see the same effect on both Firefox and Chrome. See lower left corner of Chrome window:

<img width="751" alt="Screen Shot 2019-11-07 at 9 21 37 AM" src="https://user-images.githubusercontent.com/3278623/68396760-129c7680-0140-11ea-9300-6c73ecae445a.png">

**Comment by nastacio** [comment] 2019-11-07 14:24
Same with Safari:
<img width="865" alt="Screen Shot 2019-11-07 at 9 23 38 AM" src="https://user-images.githubusercontent.com/3278623/68396914-57281200-0140-11ea-8b7b-14a3720ca0fe.png">

**Comment by kidus60** [comment] 2019-11-07 16:57
Thanks for catching this..both issues have been fixed in pr https://github.com/kabanero-io/kabanero-website/pull/289/files

**Closed as completed** 2019-11-11 20:48 UTC
